# Site settings
title: William Ganucheau
#email: williamg.online@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer and dad currently working on autonomous forklifts. On the side, I develop video games.
baseurl: ""
url: "http://williamg.me" # the base hostname & protocol for your site
twitter_username: ganashaw
github_username:  williamg

# Build settings
markdown: kramdown
permalink: /blog/:title

gems:
  - jekyll-redirect-from
