# Site settings
title: William Ganucheau
#email: williamg.online@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a junior studying computer science at Carnegie Mellon University. I like
  writing beautiful code that does cool things.
baseurl: ""
url: "http://williamg.me" # the base hostname & protocol for your site
twitter_username: wganucheau
github_username:  williamg

# Build settings
markdown: kramdown
permalink: /blog/:title

gems:
  - jekyll-redirect-from
